# Generated by Django 2.2 on 2019-04-08 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog',
            new_name='Food',
        ),
    ]
