# Generated by Django 2.1.7 on 2019-04-29 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_food_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='image_url',
        ),
        migrations.AddField(
            model_name='food',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
